name: icps
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.1.26
 # permission_handler: ^2.1.3
 # geolocator: ^2.1.0
 # permission_handler: ^2.2.0
  google_maps_flutter: ^0.2.0+6
  page_indicator: ^0.1.3
  flutter_rating: ^0.0.2
#  firebase_core: ^0.3.1+1
#  cloud_firestore: ^0.9.5+2     # new
#  firebase_auth: ^0.8.1+3
  flutter_screenutil: ^0.5.1
  dio: ^2.1.0
  http: ^0.12.0+1
  toast: ^0.1.3
  fluttertoast: ^3.0.3
  date_format: ^1.0.6
  intl: ^0.15.8
  path: ^1.6.2
  file_picker: ^1.3.3
  path_provider: ^0.5.0+1
  downloads_path_provider: ^0.0.2
  open_file: ^2.0.1+2
  fab_menu: ^0.0.2
  font_awesome_flutter: ^8.4.0
  cached_network_image: ^0.8.0
#  mailer: ^2.3.0
#  text_view:
#    path: ../text_view
simple_permissions: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/splash/SplashBg.jpg
    - assets/images/countdown/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/maps/conference_centre/
    - assets/images/maps/hotels/
    - assets/images/maps/fun_attractions/
    - assets/images/user/
   # - assets/images/activity_feed/
   # - assets/images/partners/
    - assets/images/conference/conference_audience/
    - assets/images/gallery/partners_pictures/
    - assets/images/gallery/sessions_photos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: Roboto
      fonts:
       - asset: assets/fonts/Roboto-Regular.ttf
       - asset: assets/fonts/Roboto-Bold.ttf
         weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
